// Code generated by cmd/gen-steam. DO NOT EDIT.

package steam

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
)

// Suppress unused-import complaints when no method needs a given helper.
var (
	_ = fmt.Sprintf
	_ = strconv.Itoa
	_ = json.RawMessage(nil)
	_ = url.Values(nil)
)

// PublishedFileServiceGetDetailsRequest is the request for GET /IPublishedFileService/GetDetails/v1/.
type PublishedFileServiceGetDetailsRequest struct {
	Key                       string // Access key
	PublishedFileIDs          string // uint64; Set of published file Ids to retrieve details for.
	Includetags               bool   // If true, return tag information in the returned details.
	Includeadditionalpreviews bool   // If true, return preview information in the returned details.
	Includechildren           bool   // If true, return children in the returned details.
	Includekvtags             bool   // If true, return key value tags in the returned details.
	Includevotes              bool   // If true, return vote data in the returned details.
	ShortDescription          bool   // If true, return a short description instead of the full description.
	Includeforsaledata        bool   // If true, return pricing data, if applicable.
	Includemetadata           bool   // If true, populate the metadata field.
	Language                  *int32 // optional; Specifies the localized text to return. Defaults to English.
	ReturnPlaytimeStats       uint32 // Return playtime stats for the specified number of days before today.
	AppID                     uint32
	StripDescriptionBBCode    bool    // Strips BBCode from descriptions.
	DesiredRevision           *string // optional; enum; Return the data for the specified revision.
	Includereactions          *bool   // optional; If true, then reactions to items will be returned.
	AdminQuery                bool    // Admin tool is doing a query, return hidden items
}

// PublishedFileServiceGetDetails calls GET /IPublishedFileService/GetDetails/v1/.
//
// Retrieves information about a set of published files.
func (c *Client) PublishedFileServiceGetDetails(ctx context.Context, req PublishedFileServiceGetDetailsRequest) (json.RawMessage, error) {
	args := url.Values{}
	args.Set("key", req.Key)
	args.Set("publishedfileids", req.PublishedFileIDs)
	args.Set("includetags", strconv.FormatBool(req.Includetags))
	args.Set("includeadditionalpreviews", strconv.FormatBool(req.Includeadditionalpreviews))
	args.Set("includechildren", strconv.FormatBool(req.Includechildren))
	args.Set("includekvtags", strconv.FormatBool(req.Includekvtags))
	args.Set("includevotes", strconv.FormatBool(req.Includevotes))
	args.Set("short_description", strconv.FormatBool(req.ShortDescription))
	args.Set("includeforsaledata", strconv.FormatBool(req.Includeforsaledata))
	args.Set("includemetadata", strconv.FormatBool(req.Includemetadata))
	if req.Language != nil {
		args.Set("language", strconv.FormatInt(int64(*req.Language), 10))
	}
	args.Set("return_playtime_stats", strconv.FormatUint(uint64(req.ReturnPlaytimeStats), 10))
	args.Set("appid", strconv.FormatUint(uint64(req.AppID), 10))
	args.Set("strip_description_bbcode", strconv.FormatBool(req.StripDescriptionBBCode))
	if req.DesiredRevision != nil {
		args.Set("desired_revision", *req.DesiredRevision)
	}
	if req.Includereactions != nil {
		args.Set("includereactions", strconv.FormatBool(*req.Includereactions))
	}
	args.Set("admin_query", strconv.FormatBool(req.AdminQuery))
	var out json.RawMessage
	if err := c.get(ctx, "/IPublishedFileService/GetDetails/v1/", args, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// PublishedFileServiceGetSubSectionDataRequest is the request for GET /IPublishedFileService/GetSubSectionData/v1/.
type PublishedFileServiceGetSubSectionDataRequest struct {
	Key                string // Access key
	PublishedFileID    string // uint64
	ForTableOfContents bool
	SpecificSectionid  string  // uint64
	DesiredRevision    *string // optional; enum; Return the data for the specified revision.
}

// PublishedFileServiceGetSubSectionData calls GET /IPublishedFileService/GetSubSectionData/v1/.
//
// Get sub section data (for table of contents, a specific section, or all)
func (c *Client) PublishedFileServiceGetSubSectionData(ctx context.Context, req PublishedFileServiceGetSubSectionDataRequest) (json.RawMessage, error) {
	args := url.Values{}
	args.Set("key", req.Key)
	args.Set("publishedfileid", req.PublishedFileID)
	args.Set("for_table_of_contents", strconv.FormatBool(req.ForTableOfContents))
	args.Set("specific_sectionid", req.SpecificSectionid)
	if req.DesiredRevision != nil {
		args.Set("desired_revision", *req.DesiredRevision)
	}
	var out json.RawMessage
	if err := c.get(ctx, "/IPublishedFileService/GetSubSectionData/v1/", args, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// PublishedFileServiceGetUserFileCountRequest is the request for GET /IPublishedFileService/GetUserFileCount/v1/.
type PublishedFileServiceGetUserFileCountRequest struct {
	Key                        string  // Access key
	SteamID                    string  // uint64; Steam ID of the user whose files are being requested.
	AppID                      uint32  // App Id of the app that the files were published to.
	Shortcutid                 uint32  // (Optional) Shortcut Id to retrieve published files from.
	Page                       *uint32 // optional; (Optional) Starting page for results.
	Numperpage                 *uint32 // optional; (Optional) The number of results, per page to return.
	Type_                      *string // optional; (Optional) Type of files to be returned.
	Sortmethod                 *string // optional; (Optional) Sorting method to use on returned values.
	Privacy                    uint32  // (optional) Filter by privacy settings.
	Requiredtags               string  // (Optional) Tags that must be present on a published file to satisfy the query.
	Excludedtags               string  // (Optional) Tags that must NOT be present on a published file to satisfy the query.
	RequiredKVTags             string  // protobuf message; Required key-value tags to match on.
	Filetype                   uint32  // (Optional) File type to match files to.
	CreatorAppID               uint32  // App Id of the app that published the files, only matched if specified.
	MatchCloudFilename         string  // Match this cloud filename if specified.
	CacheMaxAgeSeconds         *uint32 // optional; Allow stale data to be returned for the specified number of seconds.
	Language                   *int32  // optional; Specifies the localized text to return. Defaults to English.
	Taggroups                  string  // protobuf message; (Optional) At least one of the tags must be present on a published file to satisfy the query.
	DateRangeCreated           string  // protobuf message; (Optional) Filter to items created within this range.
	DateRangeUpdated           string  // protobuf message; (Optional) Filter to items updated within this range.
	ExcludedContentDescriptors string  // enum; (Optional) Filter out items that have these content descriptors.
	AdminQuery                 bool    // Admin tool is doing a query, return hidden items
	Totalonly                  bool    // (Optional) If true, only return the total number of files that satisfy this query.
	IDsOnly                    bool    // (Optional) If true, only return the published file ids of files that satisfy this query.
	ReturnVoteData             *bool   // optional; Return vote data
	ReturnTags                 bool    // Return tags in the file details
	ReturnKVTags               *bool   // optional; Return key-value tags in the file details
	ReturnPreviews             bool    // Return preview image and video details in the file details
	ReturnChildren             bool    // Return child item ids in the file details
	ReturnShortDescription     *bool   // optional; Populate the short_description field instead of file_description
	ReturnForSaleData          bool    // Return pricing information, if applicable
	ReturnMetadata             *bool   // optional; Populate the metadata field
	ReturnPlaytimeStats        uint32  // Return playtime stats for the specified number of days before today.
	StripDescriptionBBCode     bool    // Strips BBCode from descriptions.
	ReturnReactions            *bool   // optional; If true, then reactions to items will be returned.
	StartindexOverride         uint32  // Backwards compatible for the client.
	DesiredRevision            *string // optional; enum; Return the data for the specified revision.
	ReturnApps                 bool    // Return list of apps the items belong to
}

// PublishedFileServiceGetUserFileCount calls GET /IPublishedFileService/GetUserFileCount/v1/.
//
// Retrieves a count of files published by a user. Uses the same messages as GetUserFiles but totalonly must be true.
func (c *Client) PublishedFileServiceGetUserFileCount(ctx context.Context, req PublishedFileServiceGetUserFileCountRequest) (json.RawMessage, error) {
	args := url.Values{}
	args.Set("key", req.Key)
	args.Set("steamid", req.SteamID)
	args.Set("appid", strconv.FormatUint(uint64(req.AppID), 10))
	args.Set("shortcutid", strconv.FormatUint(uint64(req.Shortcutid), 10))
	if req.Page != nil {
		args.Set("page", strconv.FormatUint(uint64(*req.Page), 10))
	}
	if req.Numperpage != nil {
		args.Set("numperpage", strconv.FormatUint(uint64(*req.Numperpage), 10))
	}
	if req.Type_ != nil {
		args.Set("type", *req.Type_)
	}
	if req.Sortmethod != nil {
		args.Set("sortmethod", *req.Sortmethod)
	}
	args.Set("privacy", strconv.FormatUint(uint64(req.Privacy), 10))
	args.Set("requiredtags", req.Requiredtags)
	args.Set("excludedtags", req.Excludedtags)
	args.Set("required_kv_tags", req.RequiredKVTags)
	args.Set("filetype", strconv.FormatUint(uint64(req.Filetype), 10))
	args.Set("creator_appid", strconv.FormatUint(uint64(req.CreatorAppID), 10))
	args.Set("match_cloud_filename", req.MatchCloudFilename)
	if req.CacheMaxAgeSeconds != nil {
		args.Set("cache_max_age_seconds", strconv.FormatUint(uint64(*req.CacheMaxAgeSeconds), 10))
	}
	if req.Language != nil {
		args.Set("language", strconv.FormatInt(int64(*req.Language), 10))
	}
	args.Set("taggroups", req.Taggroups)
	args.Set("date_range_created", req.DateRangeCreated)
	args.Set("date_range_updated", req.DateRangeUpdated)
	args.Set("excluded_content_descriptors", req.ExcludedContentDescriptors)
	args.Set("admin_query", strconv.FormatBool(req.AdminQuery))
	args.Set("totalonly", strconv.FormatBool(req.Totalonly))
	args.Set("ids_only", strconv.FormatBool(req.IDsOnly))
	if req.ReturnVoteData != nil {
		args.Set("return_vote_data", strconv.FormatBool(*req.ReturnVoteData))
	}
	args.Set("return_tags", strconv.FormatBool(req.ReturnTags))
	if req.ReturnKVTags != nil {
		args.Set("return_kv_tags", strconv.FormatBool(*req.ReturnKVTags))
	}
	args.Set("return_previews", strconv.FormatBool(req.ReturnPreviews))
	args.Set("return_children", strconv.FormatBool(req.ReturnChildren))
	if req.ReturnShortDescription != nil {
		args.Set("return_short_description", strconv.FormatBool(*req.ReturnShortDescription))
	}
	args.Set("return_for_sale_data", strconv.FormatBool(req.ReturnForSaleData))
	if req.ReturnMetadata != nil {
		args.Set("return_metadata", strconv.FormatBool(*req.ReturnMetadata))
	}
	args.Set("return_playtime_stats", strconv.FormatUint(uint64(req.ReturnPlaytimeStats), 10))
	args.Set("strip_description_bbcode", strconv.FormatBool(req.StripDescriptionBBCode))
	if req.ReturnReactions != nil {
		args.Set("return_reactions", strconv.FormatBool(*req.ReturnReactions))
	}
	args.Set("startindex_override", strconv.FormatUint(uint64(req.StartindexOverride), 10))
	if req.DesiredRevision != nil {
		args.Set("desired_revision", *req.DesiredRevision)
	}
	args.Set("return_apps", strconv.FormatBool(req.ReturnApps))
	var out json.RawMessage
	if err := c.get(ctx, "/IPublishedFileService/GetUserFileCount/v1/", args, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// PublishedFileServiceGetUserFilesRequest is the request for GET /IPublishedFileService/GetUserFiles/v1/.
type PublishedFileServiceGetUserFilesRequest struct {
	Key                        string  // Access key
	SteamID                    string  // uint64; Steam ID of the user whose files are being requested.
	AppID                      uint32  // App Id of the app that the files were published to.
	Shortcutid                 uint32  // (Optional) Shortcut Id to retrieve published files from.
	Page                       *uint32 // optional; (Optional) Starting page for results.
	Numperpage                 *uint32 // optional; (Optional) The number of results, per page to return.
	Type_                      *string // optional; (Optional) Type of files to be returned.
	Sortmethod                 *string // optional; (Optional) Sorting method to use on returned values.
	Privacy                    uint32  // (optional) Filter by privacy settings.
	Requiredtags               string  // (Optional) Tags that must be present on a published file to satisfy the query.
	Excludedtags               string  // (Optional) Tags that must NOT be present on a published file to satisfy the query.
	RequiredKVTags             string  // protobuf message; Required key-value tags to match on.
	Filetype                   uint32  // (Optional) File type to match files to.
	CreatorAppID               uint32  // App Id of the app that published the files, only matched if specified.
	MatchCloudFilename         string  // Match this cloud filename if specified.
	CacheMaxAgeSeconds         *uint32 // optional; Allow stale data to be returned for the specified number of seconds.
	Language                   *int32  // optional; Specifies the localized text to return. Defaults to English.
	Taggroups                  string  // protobuf message; (Optional) At least one of the tags must be present on a published file to satisfy the query.
	DateRangeCreated           string  // protobuf message; (Optional) Filter to items created within this range.
	DateRangeUpdated           string  // protobuf message; (Optional) Filter to items updated within this range.
	ExcludedContentDescriptors string  // enum; (Optional) Filter out items that have these content descriptors.
	AdminQuery                 bool    // Admin tool is doing a query, return hidden items
	Totalonly                  bool    // (Optional) If true, only return the total number of files that satisfy this query.
	IDsOnly                    bool    // (Optional) If true, only return the published file ids of files that satisfy this query.
	ReturnVoteData             *bool   // optional; Return vote data
	ReturnTags                 bool    // Return tags in the file details
	ReturnKVTags               *bool   // optional; Return key-value tags in the file details
	ReturnPreviews             bool    // Return preview image and video details in the file details
	ReturnChildren             bool    // Return child item ids in the file details
	ReturnShortDescription     *bool   // optional; Populate the short_description field instead of file_description
	ReturnForSaleData          bool    // Return pricing information, if applicable
	ReturnMetadata             *bool   // optional; Populate the metadata field
	ReturnPlaytimeStats        uint32  // Return playtime stats for the specified number of days before today.
	StripDescriptionBBCode     bool    // Strips BBCode from descriptions.
	ReturnReactions            *bool   // optional; If true, then reactions to items will be returned.
	StartindexOverride         uint32  // Backwards compatible for the client.
	DesiredRevision            *string // optional; enum; Return the data for the specified revision.
	ReturnApps                 bool    // Return list of apps the items belong to
}

// PublishedFileServiceGetUserFiles calls GET /IPublishedFileService/GetUserFiles/v1/.
//
// Retrieves files published by a user.
func (c *Client) PublishedFileServiceGetUserFiles(ctx context.Context, req PublishedFileServiceGetUserFilesRequest) (json.RawMessage, error) {
	args := url.Values{}
	args.Set("key", req.Key)
	args.Set("steamid", req.SteamID)
	args.Set("appid", strconv.FormatUint(uint64(req.AppID), 10))
	args.Set("shortcutid", strconv.FormatUint(uint64(req.Shortcutid), 10))
	if req.Page != nil {
		args.Set("page", strconv.FormatUint(uint64(*req.Page), 10))
	}
	if req.Numperpage != nil {
		args.Set("numperpage", strconv.FormatUint(uint64(*req.Numperpage), 10))
	}
	if req.Type_ != nil {
		args.Set("type", *req.Type_)
	}
	if req.Sortmethod != nil {
		args.Set("sortmethod", *req.Sortmethod)
	}
	args.Set("privacy", strconv.FormatUint(uint64(req.Privacy), 10))
	args.Set("requiredtags", req.Requiredtags)
	args.Set("excludedtags", req.Excludedtags)
	args.Set("required_kv_tags", req.RequiredKVTags)
	args.Set("filetype", strconv.FormatUint(uint64(req.Filetype), 10))
	args.Set("creator_appid", strconv.FormatUint(uint64(req.CreatorAppID), 10))
	args.Set("match_cloud_filename", req.MatchCloudFilename)
	if req.CacheMaxAgeSeconds != nil {
		args.Set("cache_max_age_seconds", strconv.FormatUint(uint64(*req.CacheMaxAgeSeconds), 10))
	}
	if req.Language != nil {
		args.Set("language", strconv.FormatInt(int64(*req.Language), 10))
	}
	args.Set("taggroups", req.Taggroups)
	args.Set("date_range_created", req.DateRangeCreated)
	args.Set("date_range_updated", req.DateRangeUpdated)
	args.Set("excluded_content_descriptors", req.ExcludedContentDescriptors)
	args.Set("admin_query", strconv.FormatBool(req.AdminQuery))
	args.Set("totalonly", strconv.FormatBool(req.Totalonly))
	args.Set("ids_only", strconv.FormatBool(req.IDsOnly))
	if req.ReturnVoteData != nil {
		args.Set("return_vote_data", strconv.FormatBool(*req.ReturnVoteData))
	}
	args.Set("return_tags", strconv.FormatBool(req.ReturnTags))
	if req.ReturnKVTags != nil {
		args.Set("return_kv_tags", strconv.FormatBool(*req.ReturnKVTags))
	}
	args.Set("return_previews", strconv.FormatBool(req.ReturnPreviews))
	args.Set("return_children", strconv.FormatBool(req.ReturnChildren))
	if req.ReturnShortDescription != nil {
		args.Set("return_short_description", strconv.FormatBool(*req.ReturnShortDescription))
	}
	args.Set("return_for_sale_data", strconv.FormatBool(req.ReturnForSaleData))
	if req.ReturnMetadata != nil {
		args.Set("return_metadata", strconv.FormatBool(*req.ReturnMetadata))
	}
	args.Set("return_playtime_stats", strconv.FormatUint(uint64(req.ReturnPlaytimeStats), 10))
	args.Set("strip_description_bbcode", strconv.FormatBool(req.StripDescriptionBBCode))
	if req.ReturnReactions != nil {
		args.Set("return_reactions", strconv.FormatBool(*req.ReturnReactions))
	}
	args.Set("startindex_override", strconv.FormatUint(uint64(req.StartindexOverride), 10))
	if req.DesiredRevision != nil {
		args.Set("desired_revision", *req.DesiredRevision)
	}
	args.Set("return_apps", strconv.FormatBool(req.ReturnApps))
	var out json.RawMessage
	if err := c.get(ctx, "/IPublishedFileService/GetUserFiles/v1/", args, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// PublishedFileServiceGetUserVoteSummaryRequest is the request for GET /IPublishedFileService/GetUserVoteSummary/v1/.
type PublishedFileServiceGetUserVoteSummaryRequest struct {
	PublishedFileIDs string // uint64
}

// PublishedFileServiceGetUserVoteSummary calls GET /IPublishedFileService/GetUserVoteSummary/v1/.
//
// Get user vote summary
func (c *Client) PublishedFileServiceGetUserVoteSummary(ctx context.Context, req PublishedFileServiceGetUserVoteSummaryRequest) (json.RawMessage, error) {
	args := url.Values{}
	args.Set("publishedfileids", req.PublishedFileIDs)
	var out json.RawMessage
	if err := c.get(ctx, "/IPublishedFileService/GetUserVoteSummary/v1/", args, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// PublishedFileServiceQueryFilesRequest is the request for GET /IPublishedFileService/QueryFiles/v1/.
type PublishedFileServiceQueryFilesRequest struct {
	Key                          string  // Access key
	QueryType                    uint32  // enumeration EPublishedFileQueryType in clientenums.h
	Page                         uint32  // Current page
	Cursor                       string  // Cursor to paginate through the results (set to '*' for the first request).  Prefer this over using the page parameter, as it will allow you to do deep pagination.  When used, the page parameter will be ignored.
	Numperpage                   *uint32 // optional; (Optional) The number of results, per page to return.
	CreatorAppID                 uint32  // App that created the files
	AppID                        uint32  // App that consumes the files
	Requiredtags                 string  // Tags to match on. See match_all_tags parameter below
	Excludedtags                 string  // (Optional) Tags that must NOT be present on a published file to satisfy the query.
	MatchAllTags                 *bool   // optional; If true, then items must have all the tags specified, otherwise they must have at least one of the tags.
	RequiredFlags                string  // Required flags that must be set on any returned items
	OmittedFlags                 string  // Flags that must not be set on any returned items
	SearchText                   string  // Text to match in the item's title or description
	Filetype                     uint32  // EPublishedFileInfoMatchingFileType
	ChildPublishedFileID         string  // uint64; Find all items that reference the given item.
	Days                         uint32  // If query_type is k_PublishedFileQueryType_RankedByTrend, then this is the number of days to get votes for [1,7].
	IncludeRecentVotesOnly       bool    // If query_type is k_PublishedFileQueryType_RankedByTrend, then limit result set just to items that have votes within the day range given
	CacheMaxAgeSeconds           *uint32 // optional; Allow stale data to be returned for the specified number of seconds.
	Language                     *int32  // optional; Language to search in and also what gets returned. Defaults to English.
	RequiredKVTags               string  // protobuf message; Required key-value tags to match on.
	Taggroups                    string  // protobuf message; (Optional) At least one of the tags must be present on a published file to satisfy the query.
	DateRangeCreated             string  // protobuf message; (Optional) Filter to items created within this range.
	DateRangeUpdated             string  // protobuf message; (Optional) Filter to items updated within this range.
	ExcludedContentDescriptors   string  // enum; (Optional) Filter out items that have these content descriptors.
	AdminQuery                   bool    // Admin tool is doing a query, return hidden items
	SpecialFilter                string  // enum; Additional special filtering
	AppidsRequiredForUse         uint32  // DLC required to use the item
	ExcludedAppidsRequiredForUse uint32  // Exclude this DLC required to use the item
	SearchTextTarget             string  // enum; Can be used to search only title or description, instead of both (by default)
	Totalonly                    bool    // (Optional) If true, only return the total number of files that satisfy this query.
	IDsOnly                      bool    // (Optional) If true, only return the published file ids of files that satisfy this query.
	ReturnVoteData               bool    // Return vote data
	ReturnTags                   bool    // Return tags in the file details
	ReturnKVTags                 bool    // Return key-value tags in the file details
	ReturnPreviews               bool    // Return preview image and video details in the file details
	ReturnChildren               bool    // Return child item ids in the file details
	ReturnShortDescription       bool    // Populate the short_description field instead of file_description
	ReturnForSaleData            bool    // Return pricing information, if applicable
	ReturnMetadata               *bool   // optional; Populate the metadata
	ReturnPlaytimeStats          uint32  // Return playtime stats for the specified number of days before today.
	ReturnDetails                bool    // By default, if none of the other 'return_*' fields are set, only some voting details are returned. Set this to true to return the default set of details.
	StripDescriptionBBCode       bool    // Strips BBCode from descriptions.
	DesiredRevision              *string // optional; enum; Return the data for the specified revision.
	ReturnReactions              *bool   // optional; If true, then reactions to items will be returned.
}

// PublishedFileServiceQueryFiles calls GET /IPublishedFileService/QueryFiles/v1/.
//
// Performs a search query for published files
func (c *Client) PublishedFileServiceQueryFiles(ctx context.Context, req PublishedFileServiceQueryFilesRequest) (json.RawMessage, error) {
	args := url.Values{}
	args.Set("key", req.Key)
	args.Set("query_type", strconv.FormatUint(uint64(req.QueryType), 10))
	args.Set("page", strconv.FormatUint(uint64(req.Page), 10))
	args.Set("cursor", req.Cursor)
	if req.Numperpage != nil {
		args.Set("numperpage", strconv.FormatUint(uint64(*req.Numperpage), 10))
	}
	args.Set("creator_appid", strconv.FormatUint(uint64(req.CreatorAppID), 10))
	args.Set("appid", strconv.FormatUint(uint64(req.AppID), 10))
	args.Set("requiredtags", req.Requiredtags)
	args.Set("excludedtags", req.Excludedtags)
	if req.MatchAllTags != nil {
		args.Set("match_all_tags", strconv.FormatBool(*req.MatchAllTags))
	}
	args.Set("required_flags", req.RequiredFlags)
	args.Set("omitted_flags", req.OmittedFlags)
	args.Set("search_text", req.SearchText)
	args.Set("filetype", strconv.FormatUint(uint64(req.Filetype), 10))
	args.Set("child_publishedfileid", req.ChildPublishedFileID)
	args.Set("days", strconv.FormatUint(uint64(req.Days), 10))
	args.Set("include_recent_votes_only", strconv.FormatBool(req.IncludeRecentVotesOnly))
	if req.CacheMaxAgeSeconds != nil {
		args.Set("cache_max_age_seconds", strconv.FormatUint(uint64(*req.CacheMaxAgeSeconds), 10))
	}
	if req.Language != nil {
		args.Set("language", strconv.FormatInt(int64(*req.Language), 10))
	}
	args.Set("required_kv_tags", req.RequiredKVTags)
	args.Set("taggroups", req.Taggroups)
	args.Set("date_range_created", req.DateRangeCreated)
	args.Set("date_range_updated", req.DateRangeUpdated)
	args.Set("excluded_content_descriptors", req.ExcludedContentDescriptors)
	args.Set("admin_query", strconv.FormatBool(req.AdminQuery))
	args.Set("special_filter", req.SpecialFilter)
	args.Set("appids_required_for_use", strconv.FormatUint(uint64(req.AppidsRequiredForUse), 10))
	args.Set("excluded_appids_required_for_use", strconv.FormatUint(uint64(req.ExcludedAppidsRequiredForUse), 10))
	args.Set("search_text_target", req.SearchTextTarget)
	args.Set("totalonly", strconv.FormatBool(req.Totalonly))
	args.Set("ids_only", strconv.FormatBool(req.IDsOnly))
	args.Set("return_vote_data", strconv.FormatBool(req.ReturnVoteData))
	args.Set("return_tags", strconv.FormatBool(req.ReturnTags))
	args.Set("return_kv_tags", strconv.FormatBool(req.ReturnKVTags))
	args.Set("return_previews", strconv.FormatBool(req.ReturnPreviews))
	args.Set("return_children", strconv.FormatBool(req.ReturnChildren))
	args.Set("return_short_description", strconv.FormatBool(req.ReturnShortDescription))
	args.Set("return_for_sale_data", strconv.FormatBool(req.ReturnForSaleData))
	if req.ReturnMetadata != nil {
		args.Set("return_metadata", strconv.FormatBool(*req.ReturnMetadata))
	}
	args.Set("return_playtime_stats", strconv.FormatUint(uint64(req.ReturnPlaytimeStats), 10))
	args.Set("return_details", strconv.FormatBool(req.ReturnDetails))
	args.Set("strip_description_bbcode", strconv.FormatBool(req.StripDescriptionBBCode))
	if req.DesiredRevision != nil {
		args.Set("desired_revision", *req.DesiredRevision)
	}
	if req.ReturnReactions != nil {
		args.Set("return_reactions", strconv.FormatBool(*req.ReturnReactions))
	}
	var out json.RawMessage
	if err := c.get(ctx, "/IPublishedFileService/QueryFiles/v1/", args, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// SteamRemoteStorageGetCollectionDetailsRequest is the request for POST /ISteamRemoteStorage/GetCollectionDetails/v1/.
type SteamRemoteStorageGetCollectionDetailsRequest struct {
	Collectioncount  uint32   // Number of collections being requested
	PublishedFileIDs []string // uint64; collection ids to get the details for
}

// SteamRemoteStorageGetCollectionDetails calls POST /ISteamRemoteStorage/GetCollectionDetails/v1/.
func (c *Client) SteamRemoteStorageGetCollectionDetails(ctx context.Context, req SteamRemoteStorageGetCollectionDetailsRequest) (json.RawMessage, error) {
	args := url.Values{}
	args.Set("collectioncount", strconv.FormatUint(uint64(req.Collectioncount), 10))
	for i, v := range req.PublishedFileIDs {
		args.Set(fmt.Sprintf("publishedfileids[%d]", i), v)
	}
	var out json.RawMessage
	if err := c.postForm(ctx, "/ISteamRemoteStorage/GetCollectionDetails/v1/", args, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// SteamRemoteStorageGetPublishedFileDetailsRequest is the request for POST /ISteamRemoteStorage/GetPublishedFileDetails/v1/.
type SteamRemoteStorageGetPublishedFileDetailsRequest struct {
	Itemcount        uint32   // Number of items being requested
	PublishedFileIDs []string // uint64; published file id to look up
}

// SteamRemoteStorageGetPublishedFileDetails calls POST /ISteamRemoteStorage/GetPublishedFileDetails/v1/.
func (c *Client) SteamRemoteStorageGetPublishedFileDetails(ctx context.Context, req SteamRemoteStorageGetPublishedFileDetailsRequest) (json.RawMessage, error) {
	args := url.Values{}
	args.Set("itemcount", strconv.FormatUint(uint64(req.Itemcount), 10))
	for i, v := range req.PublishedFileIDs {
		args.Set(fmt.Sprintf("publishedfileids[%d]", i), v)
	}
	var out json.RawMessage
	if err := c.postForm(ctx, "/ISteamRemoteStorage/GetPublishedFileDetails/v1/", args, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// SteamRemoteStorageGetUGCFileDetailsRequest is the request for GET /ISteamRemoteStorage/GetUGCFileDetails/v1/.
type SteamRemoteStorageGetUGCFileDetailsRequest struct {
	SteamID *string // optional; uint64; If specified, only returns details if the file is owned by the SteamID specified
	Ugcid   string  // uint64; ID of UGC file to get info for
	AppID   uint32  // appID of product
}

// SteamRemoteStorageGetUGCFileDetails calls GET /ISteamRemoteStorage/GetUGCFileDetails/v1/.
func (c *Client) SteamRemoteStorageGetUGCFileDetails(ctx context.Context, req SteamRemoteStorageGetUGCFileDetailsRequest) (json.RawMessage, error) {
	args := url.Values{}
	if req.SteamID != nil {
		args.Set("steamid", *req.SteamID)
	}
	args.Set("ugcid", req.Ugcid)
	args.Set("appid", strconv.FormatUint(uint64(req.AppID), 10))
	var out json.RawMessage
	if err := c.get(ctx, "/ISteamRemoteStorage/GetUGCFileDetails/v1/", args, &out); err != nil {
		return nil, err
	}
	return out, nil
}
